import Head from 'next/head';
import NextLink from 'next/link';
import { useState } from 'react';
import Navbar from '../components/Navbar';
import { Router, useRouter } from 'next/router';

import {
	Box,
	Flex,
	Heading,
	Text,
	Input,
	Center,
	Image,
	SimpleGrid,
	useDisclosure,
	Link,
	Button,
	Modal,
	ModalOverlay,
	ModalContent,
	ModalHeader,
	ModalCloseButton,
	ModalBody,
	ModalFooter,
	InputGroup,
	InputLeftAddon,
	CloseButton,
} from '@chakra-ui/react';
import { HamburgerIcon } from '@chakra-ui/icons';

const Card = (props) => {
	return (
		<Box
			bg={props.color}
			m={2}
			borderRadius='20px'
			w='240px'
			h='280px'
			p={2}
			filter=' drop-shadow(2px 6px 4px rgba(0, 0, 0, 0.4))'
			position='relative'>
			<Head>
				<title>Bonding Over Bindings</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Heading
				fontSize='28px'
				fontWeight='bold'
				textDecoration='underline'
				mt='40px'
				ml='28px'
				mr='28px'>
				{props.genre}
			</Heading>
			<Text top='200px' right='32px' position='absolute' textColor='#ffffff' fontSize='18px'>
				Learn More
			</Text>
		</Box>
	);
};

function LandingPage() {
	const [display, setDisplay] = useState('none');
	const { isOpen, onOpen, onClose } = useDisclosure();
	const router = useRouter();

	return (
		<Box>
			<Box mr='5%' ml='5%'>
				<Navbar />

				<Flex>
					{/* <Box
					backgroundImage="url('herosection.svg')"
					height='330px'
					width='100%'
					bgPosition='center'
					bgRepeat='no-repeat'> */}
					<Box bg='#635280' height='330px' width='100%' maxHeight='330px'>
						<Heading fontWeight='800' color='white' fontSize='42px' ml={10} mt={10}>
							A Navi Mumbai based reading community started
							<br />
							By students,
							<br /> For students.
						</Heading>
					</Box>
				</Flex>
				<br />
				<br />
				<Box position='relative'>
					<Box
						position='absolute'
						h='100%'
						w='100%'
						bgGradient='linear(360deg, #FFFFFF -2.7%, rgba(255, 255, 255, 0) 94.98%)'></Box>
					<Text fontSize='36px' fontWeight='semibold'>
						What is a book club?
					</Text>
					<Text fontSize='20px' color='#635280'>
						A group of people who come together to discuss the book they read.
					</Text>
					<br />
					<Text fontSize='36px' fontWeight='semibold'>
						How is the BondingOverBindings Book Club like?
					</Text>
					<Text fontSize='20px' color='#635280'>
						A group of people who come together to discuss the book they read.
					</Text>
					<br />
					<Text fontSize='36px' fontWeight='semibold'>
						What do I have to do?
					</Text>
					<Text fontSize='20px' color='#635280'>
						A group of people who come together to discuss the book they read.
					</Text>
					<br />
				</Box>
				<Center>
					<Button
						size='md'
						height='48px'
						width='200px'
						border='2px'
						borderColor='black.500'
						borderRadius='0px'
						bgColor='#635280'
						textColor='#ffffff'
						onClick={() => router.push('/about')}>
						Read More
					</Button>
				</Center>
				<br />
				<br />
				<br />
				<br />

				<Heading fontSize='42px'>Books selected for the Oct-Nov-Dec session :</Heading>
				<br />
				<br />
			</Box>
			<Box bgColor='#445743' height='120px'>
				<Flex w='100%' h='100%' align='center'>
					<Text
						fontSize='36px'
						fontWeight='bold'
						textDecoration='underline'
						textColor='#ffffff'
						mr='5%'
						ml='5%'>
						select the genre you’d prefer
					</Text>
				</Flex>
			</Box>
			<br />
			<br />
			<Box mr='5%' ml='5%'>
				<Center>
					<SimpleGrid columns={{ sm: 2, md: 3, lg: 4 }} spacing={10}>
						<Card genre='Fiction' color='#E7A7AA' />
						<Card genre='Short Story Collection ' color='#99D2EF' />
						<Card genre='Fantasy Fiction' color='#8FBE8E' />
						<Card genre='Science Fiction' color='#FDD594' />
						<Card genre='Socio Political' color='#B7EAC8' />
						<Card genre='Tech Related' color='#ECA892' />
						<Card genre='Historical Fiction' color='#EDC0EE' />
						<Card genre='Essay Collection' color='#FFD8D8' />
						<Card genre='Poetry Collection' color='#BBB3DC' />
						<Card genre='Young Adult Fiction' color='#81FFD1' />
					</SimpleGrid>
				</Center>
			</Box>
		</Box>
	);
}
export default LandingPage;
